export enum LoginActionTypes {
    INPUT_NICKNAME = 'INPUT_NICKNAME',
    INPUT_EMAIL = 'INPUT_EMAIL',
    INPUT_PASSWORD = 'INPUT_PASSWORD',
    INPUT_ERROR = 'INPUT_ERROR',
    OFF_ERROR = 'OFF_ERROR'
}
